#ifndef SYNCHRONIZER_HPP
#define SYNCHRONIZER_HPP

#include <time.h>
#include <thrift/ClockServer.h> //This is where the header is from the autogenerated folder
#include <yarp/os/Time.h>
#include <yarp/os/Network.h>
#include <yarp/os/BufferedPort.h>

#include <yarp/os/LogStream.h>
#include <yarp/os/Log.h>


struct InternalData{

    struct{
        std::string clientPortName;
        std::string serverPortName;
        unsigned numberOfSteps;
    } configuration;

    yarp::os::Port clientPort;
    gazebo::ClockServer clockServer;
};

#endif // SYNCHRONIZER_HPP

